### ISSUE TITLE
Reason behind setting max depth = 40000

### ISSUE THREAD

**Issue by AhmadAshraf2** [BitMEXResearch/forkmonitor#178]
Why is the value of max depth [here](https://github.com/BitMEXResearch/forkmonitor/blob/master/app/models/node.rb#L598) hard coded to 40,000. 

Is it a check to only retrieve blocks which are roughly one year old?

Also why only check the last 10 blocks [here](https://github.com/BitMEXResearch/forkmonitor/blob/5fc7b0167d4c9b86541355656f26449deac28c42/app/models/block.rb#L624)

**Comment by Sjors** [comment]
Re 40,000: I can't remember, but most likely to prevent wasting time trying to fetch very old (stale) blocks that probably nobody has anymore.

Re 10: we regularly check if any  our own nodes have the full block that our database is missing. If they still don't have it after 10 blocks, they never will. This is because nodes don't ask their peers for block data for blocks with less proof-of-work than the longest chain.
